kind: ConfigMap
apiVersion: v1
metadata:
  name: cloud-command-php
data:
  zzz-custom.ini: |
    ; Basic configuration
    upload_max_filesize = 100M
    post_max_size = 100M
    memory_limit=1600M
    log_level = notice
    date.timezone = UTC
    cgi.fix_pathinfo=0
    ; Cache configuration
    opcache.fast_shutdown=1
    opcache.enable_cli=1
    # Opcache for cloud command is configured for minimal caching and large potential resource usage
    opcache.memory_consumption=256
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=15000
    opcache.revalidate_freq=0
    realpath_cache_size=64k
    realpath_cache_ttl=1
  zzz-custom.conf: |
    [www]
    ; Add status page output, could also add further configuration params here
    ; Status page will have to be accessible thru fcgi via nginx
    pm.status_path = /php-fpm-status
    ping.path = /php-fpm-ping

    ; Get fresh php processes in case some errant script has a leak
    pm.max_requests = 200

    ; Cloud command is not actually using php-fpm, it uses the fpm image to share dependencies with the drupal image
    ; So lets set it to ondemand and allow it to run zero children most of the time
    pm = ondemand
    pm.max_children = 5
