apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Values.ingress.service.name }}
                port:
                  number: {{ $.Values.ingress.service.port }}
            pathType: ImplementationSpecific
    {{- end }}
