{{- if .Values.xdebug.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xdebug
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  replicas: 1
  serviceName: "xdebug"
  selector:
    matchLabels:
      component: "xdebug"
  template:
    metadata:
      labels:
        component: "xdebug"
    spec:
{{- if .Values.initContainer.enabled }}
      initContainers:
{{ include "drupal.initContainer" . | indent 6 }}
{{- end }}
      containers:
        - name: "xdebug"
          image: {{ .Values.xdebug.image }}
          env:
            - name: "XDEBUG_REMOTE_HOST"
              value: {{ .Values.xdebug.remoteHost }}
{{- include "drupal.env" . | indent 12 }}
{{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.xdebug.resources | indent 12 }}
          volumeMounts:
            - name: "php-configmap"
              mountPath: "/usr/local/etc/php/conf.d/zzz-custom.ini"
              subPath: "zzz-custom.ini"
            - name: "php-configmap"
              mountPath: "/usr/local/etc/php-fpm.d/zzz-custom.conf"
              subPath: "zzz-custom.conf"
            - name: "drupal-source"
              mountPath: "/var/www/docroot"
              subPath: "docroot"
            - name: "drupal-source"
              mountPath: "/var/www/config"
              subPath: "config"
            - name: "drupal-source"
              mountPath: "/var/www/vendor"
              subPath: "vendor"
            - name: "drupal-source"
              mountPath: "/var/www/composer.json"
              subPath: "composer.json"
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
      volumes:
        - name: "php-configmap"
          configMap:
            name: "xdebug-php"
{{- if .Values.applicationVolume.enabled }}
        - name: "drupal-source"
          hostPath:
            path: {{ .Values.applicationVolume.path }}
{{- else }}
        - name: "drupal-source"
          emptyDir: {}
{{- end  }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
{{- end }}
