{{- if .Values.php.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php
  minReplicas: {{ .Values.php.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.php.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.php.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.php.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.php.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.php.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
