apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  ports:
    - port: {{ .Values.php.service.port }}
      targetPort: {{ .Values.php.service.targetPort }}
      name: {{ .Values.php.service.targetName }}
  selector:
    component: "php"
