{{ if and (.Values.ingress.tls.enabled) (.Values.ingress.tls.custom.crt) (.Values.ingress.tls.custom.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
type: "kubernetes.io/tls"
data:
  tls.crt: {{ .Values.ingress.tls.custom.crt }}
  tls.key: {{ .Values.ingress.tls.custom.key }}
{{ end }}
